### ISSUE TITLE
Strange animation

### ISSUE THREAD

**Issue by lorisgir** [saket/InboxRecyclerView#10]
If I have any layout above the RecylerView and then I click on one of my items, the open animation is just fine, but the closing one behave strangely

**Comment by saket** [comment]
You'll have to help me help you here :) 

Can you share a gist of your layout and a video?

**Comment by lorisgir** [comment]
Sure.
I can replicate the problem by just adding a view in your sample app.
As you can see I just added a frame layout above the recycler.
<img width="519" alt="screen shot 2018-09-24 at 20 27 07" src="https://user-images.githubusercontent.com/17686750/45971007-48fc5c80-c038-11e8-8f5a-34102db03384.png">

Here a video of the problem: https://streamable.com/3yu2g
First part is at normal speed, second one is at 10x slow.
It appears that the recycler goes down a bit and then return to the normal position after the animation stops.
I'm just a newbie of Android, and I'm not used to see kotlin code. So I can't be helpful.

**Comment by saket** [comment]
That doesn't look nice. I'll try reproducing it this weekend and see what's going wrong.

**Comment by saket** [comment]
Sorry for the late reply but I just realized that this is happening because your `InboxRecyclerView` and `ExpandablePageLayout` do not have the same bounds. If you look at the [sample app](https://github.com/saket/InboxRecyclerView/blob/828580b586b073f8e3205dab2bb2f7aec7d1966f/sample/src/main/res/layout/activity_inbox.xml#L15), you'll notice that the RV has a paddingTop to compensate for this.

That said, I've improved how the coordinates are calculated so you won't have to deal with this. It'll be included in the next major release. If you want to try it out early you use the SNAPSHOT:

```
implementation 'me.saket:inboxrecyclerview:2.0.0-SNAPSHOT'
```

**Comment by saket** [comment]
I'm late by many weekends but I just realized that this is happening because your `InboxRecyclerView` and `ExpandablePageLayout` do not have the same bounds. If you look at the [sample app](https://github.com/saket/InboxRecyclerView/blob/828580b586b073f8e3205dab2bb2f7aec7d1966f/sample/src/main/res/layout/activity_inbox.xml#L15), you'll notice that the RV has a paddingTop to compensate for this.

That said, I've improved how the coordinates are calculated so you won't have to deal with this. It'll be included in the next major release. If you want to try it out early you use the SNAPSHOT:

```
implementation 'me.saket:inboxrecyclerview:2.0.0-SNAPSHOT'
```
